User:
  type: entity
  table: product
  id:
    id:
      type: integer
      nullable: false
      id: true
      column: id
      options:
        unsinged: false
      generator:
        strategy: Auto
  fields:
    name:
      type: string
      nullable: false
      length: 256
      options:
        fixed: false
    price:
      type: string
      nullable: false
      length: 256
      options:
        fixed: false
    description:
      type: string
      nullable: true
      length: 256
      options:
        fixed: false
    image:
      type: string
      nullable: true
      length: 256
      options:
      fixed: false

lifecycleCallbacks: {}